// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqO6CoxeRMxSBtbk1yqVlKX5kaLk3TRhc',
    appId: '1:807237253600:web:593bd1051c52f66890d385',
    messagingSenderId: '807237253600',
    projectId: 'stroke-spoiler',
    authDomain: 'stroke-spoiler.firebaseapp.com',
    storageBucket: 'stroke-spoiler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnjocrvc5FCpF9J7qhcUC-FiHNf8ofkM',
    appId: '1:807237253600:android:6f74883623a55f4f90d385',
    messagingSenderId: '807237253600',
    projectId: 'stroke-spoiler',
    storageBucket: 'stroke-spoiler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdS9fnZDsbIz0gC0DyP1ZYExlGJJmA7w',
    appId: '1:807237253600:ios:bd573f44c869f68a90d385',
    messagingSenderId: '807237253600',
    projectId: 'stroke-spoiler',
    storageBucket: 'stroke-spoiler.firebasestorage.app',
    iosBundleId: 'org.wapsudal.strokespoiler',
  );
}
